#/bin/bash
#######bin path
scriptp=`dirname "$(realpath $0)"`
binpath="$scriptp/bin"
DiscoVistap="" # https://github.com/esayyari/DiscoVista.git

######### Raw inout 
GenetreeLsfs=`realpath $1` #generated by b.phylogeny.sh 
SpeciesTree=`realpath $2` # Anstral result

#####
mkdir trees
cd trees 
ln -s $GenetreeLsfs estimated_gene_trees.tree
ln -s $SpeciesTree estimated_species_tree.tree 
cd ..
$DiscoVistap/discoVista.py -a species.order -m 5 -p trees/ -o trees/anot
