#/bin/bash
#######bin path
scriptp=`dirname "$(realpath $0)"`
binpath="$scriptp/bin"

################ raw path
dir1=`pwd`
Mafdir= "" # maf path were generated by b.Mergemaf_filter.sh
SDRpath="" # the path of SDR path
#####################
cat $scriptp/example/filter_run.txt |grep "^COLBRE"|while read lineK
do
    line=`echo $lineK |awk '{print $2}'`
    spn=`echo $line|awk '{print $2}' |awk -F "_" '{print $1}'`
    name=`grep $spn $scriptp/../species.txt |awk '{print $1}'`
    SDRr="$SDRpath/$name.strata.bed"
    mafa_raw=$Mafdir/$line/$line.noncoding.nonrepeat.maf
    fullmaf=$Mafdir/$line/$line.all.noncoding.nonrepeat.maf
    m1=`echo -e $lineK |cut -f2 -d " "|sed 's/_/-/'`
    m2=`echo -e $lineK |cut -f3- -d " "|sed 's/\s\+/-/g'`
    python $binpath/filter_maf.py $mafa_raw $m1 $m2 $fullmaf
    awk '{print $NF}' $SDRr |sort |uniq |while read k
    do
        grep -w $k $SDRr|sort -k1,1V -k2,2n  >tm_strata_${spn}_${k}.bed
        outm=$fullmaf.$k.maf
        echo "perl $binpath/get_maf_by_bed_from_multi.pl -slice -spe $spn $fullmaf tm_strata_${spn}_${k}.bed >$outm"
        echo "python $binpath/Runbaseml_Raxml.py $outm $dir1/$line/$k 100 $spn"
    done
done

python $binpath/GetMutatiomRatio.py $dir1 male_muation.txt
python $binpath/Malemutationbias_Confidentce.py male_muation.txt 
