#/bin/bash
#######bin path
scriptp=`dirname "$(realpath $0)"`
binpath="$scriptp/bin"
pamlpath="" #Paml path

######################## Raw input

dir1=`pwd`
Mafdir="" # maf path were generated by b.Mergemaf_filter.sh
SDRpath="" # the path of SDR path

###################
awk '{print $2}' $scriptp/example/filter_run.txt |grep "^COLBRE" |while read line
do
    spn=`echo $line|awk '{print $1}'| awk -F "_" '{print $1}'`
    name=`grep $spn $scriptp/../species.txt |awk '{print $1}'`
    SDRr="$SDRpath/$name.strata.bed"
    mafa=$Mafdir/$line/$line.all.noncoding.nonrepeat.maf
    awk '{print $NF}' $SDRr |sort |uniq |while read k
    do
        outm=$mafa.$k.maf
        rundir=$dir1/$line/$k
        if [ ! -d $rundir ];then
            mkdir -p $rundir
        fi
        echo "python $binpath/MergeAlign.py $outm $rundir/species.nwk $rundir/Alignment.phy"
        echo "cd $rundir" >$rundir/Runbaseml.sh
        echo "ln -s $scriptp/example/scale_time/Baseml.ctl" >>$rundir/Runbaseml.sh
        echo "$pamlpath/baseml Baseml.ctl" >>$rundir/Runbaseml.sh
        echo "ln -s $scriptp/example/scale_time/runboost.ctl" >>$rundir/Runbaseml.sh
        echo "$pamlpath/baseml runboost.ctl" >>$rundir/Runbaseml.sh
        echo "ln -s $scriptp/example/boost.ctl" >>$rundir/Runbaseml.sh
        echo "$pamlpath/baseml boost.ctl"
        sh $rundir/Runbaseml.sh
    done
    
done

######################
cd $dir1
mkdir Rawdata 
cd Rawdata
cat $scriptp/example/filter_run.txt|awk '{print $2}' |while read line ;do ln -s ../../$line/S0/mlbk1 Rawdata/${line}_S0.txt ;done
do
    python $binpath/Get95confidence.py $scriptp/scale/nodetable.json Rawdata/${line}_S0.txt $line confidence/$line.95confidence.txt 
done
cd ..
echo ARIPRA `python $binpath/Calculatetime.py confidence/ARIPRA.95confidence.txt 87.62 0.78 ZW` >>divertime.txt
echo CHRMAR `python $binpath/Calculatetime.py confidence/CHRMAR.95confidence.txt 74.70 1.02 ZW` >>divertime.txt
echo COLBRE `python $binpath/Calculatetime.py  confidence/COLBRE.95confidence.txt 77.53 1.51 XY` >>divertime.txt
echo CORSAR_CORCIL  `$binpath/Calculatetime.py  confidence/CORSAR_CORCIL.95confidence.txt 60.93 0.87 ZW` >>divertime.txt
echo GEHMUT `python $binpath/Calculatetime.py  confidence/GEHMUT.95confidence.txt 73.69 0.84 ZW` >>divertime.txt
echo HEMFRE `python $binpath/Calculatetime.py  confidence/HEMFRE.95confidence.txt 46.10 1.05 ZW` >>divertime.txt
echo HEMMAB `python $binpath/Calculatetime.py  confidence/HEMMAB.95confidence.txt 46.10 1.29 XY` >>divertime.txt
echo NEPLEV `python $binpath/Calculatetime.py  confidence/NEPLEV.95confidence.txt 55.84 0.74 ZW` >>divertime.txt
echo PARSTU `python $binpath/Calculatetime.py  confidence/PARSTU.95confidence.txt 63.88 0.84 ZW` >>divertime.txt
echo PHYWIR `python $binpath/Calculatetime.py  confidence/PHYWIR.95confidence.txt 80.58 1.02 ZW` >>divertime.txt
echo SPHMIN `python $binpath/Calculatetime.py  confidence/SPHMIN.95confidence.txt 87.62 1.37 XY` >>divertime.txt
