##/bin/bash
Ancestralblock_file=$1 #ancestral karyotype file generated by 04.Karyotpe step 
SDRbedpath=$2 #SDR regions file with bed formate, generated by 01.Identify_sexchromosome
###SDR block
n=3
while (n<86)
do
  s1=`expr $n + 3`
  cut -f1-2,$n-$s1 $Ancestralblock_file|grep -w "GAC" |awk '{print $4"\t"$5"\t"$6"\t"$1"\t"$2"\t"$3}' |sort -k1,1V -k2,2n >tpm1
  spn=`head -1 tpm1 |awk '{print $NF}'`
  SDRfile="$SDRbedpath/$spn.bed"
  bedtools coverage -a tmp1 -b $SDRfile -wa |awk '{if($NF>0)print $4"\t"$5"\t1"}' >$spn.sdr.block.txt
done
cat *sdr.block.txt | sort |uniq -c >all.SDR.Block.txt
awk '{print $1"\t"$2"\t"$NF}' $Ancestralblock_file |while read AnchrID blockid length
do
  number1=`awk '{if($3=="'$blockid'")print $1}'`
  if [[ -z "$number1" ]];then
    number1="0"
  fi
  echo -e "GAC$AnchrID\tBlock$blockid\t$number1\t$length"
done >>SDR_regins_number.txt 

##
Rscript ../bin/simulate_visualize.nonrandomness.r SDR_regins_number.txt plot.pdf stats.out
